---
version: '2'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      ADMIN_EMAIL: operations@aperim.com
      PIHOLE_DNS_: 127.0.0.1#5353
      DNSSEC: 'true'
      DNS_BOGUS_PRIV: 'false'
      DHCP_ACTIVE: 'false'
      IPv6: 'true'
      TEMPERATUREUNIT: c
      WEBUIBOXEDLAYOUT: boxed
      QUERY_LOGGING: 'true'
      INTERFACE: eth0
    volumes:
    - config-pihole:/etc/pihole/
    - config-dnsmasq:/etc/dnsmasq.d/
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    dns:
    - "::1"
    - 127.0.0.1
    cap_add:
    - NET_ADMIN
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: udp://log001.public-servers.sy3.aperim.net:12201
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: dns,pihole,sw3
  unbound:
    container_name: unbound
    image: ghcr.io/aperim/unbound:latest
    restart: unless-stopped
    network_mode: host
    environment:
      PRIVATE_DOMAINS: aperim.net,rlyrly.net,plex.direct,belcastro.net,mdt.zone,mdte.co
      PRIVATE_ARPA: ns1.aperim.com,ns2.aperim.com,ns3.aperim.com,ns4.aperim.net,ns5.aperim.net,ns6.aperim.net
    volumes:
    - config-unbound:/opt/unbound/etc/unbound/
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: gelf
      options:
        gelf-address: udp://log001.public-servers.sy3.aperim.net:12201
        gelf-compression-type: none
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: dns,unbound,sw3
volumes:
  config-pihole:
  config-dnsmasq:
  config-unbound:
